project_name: whisper-fed-test
run_name: test-run-1

# Path to HuggingFace or local dataset
dataset:
  name: spc-fed-dataset
  path: ./data/spc_dataset.parquet
  streaming: false
  use_auth_token: false

# Whisper model configuration
model:
  name_or_path: openai/whisper-small
  compute_type: float16
  gradient_checkpointing: true

# Training configuration
training:
  output_dir: ./checkpoints/
  num_train_epochs: 1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 2
  learning_rate: 1e-4
  save_steps: 500
  eval_steps: 500
  logging_steps: 50
  save_total_limit: 2
  fp16: true
  do_eval: true
  evaluation_strategy: steps

# Weights & Biases logging
wandb:
  enable: true
  project: whisper-fed-test
  entity: aryan-dutt

# LoRA / minLoRA (optional)
lora:
  enable: false